abstract: CSS Selector to XPath compiler
author: Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: HTML-Selector-XPath
no_index: 
  directory: 
    - inc
    - t
version: 0.02
