---
abstract: 'CSS Selector to XPath compiler'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Base: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Selector-XPath
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
